### ISSUE TITLE
Metrics accuracy

### ISSUE THREAD

**Issue by mlabour** [heroku/heroku-javaagent#2]
Hi

The test has been performed on  the following machine:
Ubuntu 12.04.2 LTS, Precise Pangolin
Linux ubuntu 3.2.0-43-generic-pae #68-Ubuntu SMP Wed May 15 03:55:10 UTC 2013 i686 i686 i386 GNU/Linux

I use Runtime.getRuntime().freeMemory() and Runtime.getRuntime().totalMemory() and i am also using the heroku memory logging event.

I don't understand why the numbers returned by Runtime and the numbers returned by javaagent are different. I would be grateful for any help. 

2013-05-23 12:54:15,955  INFO  scheduler_Worker-1 
-- Runtime Statistics
    |
     -- available processors:2
     -- total memory:61669376
     -- free memory:51671048

heroku-javaagent: JVM Memory Usage     (Heap): used: 21M committed: 39M max:466M
heroku-javaagent: JVM Memory Usage (Non-Heap): used: 31M committed: 32M max:180M
heroku-javaagent: JVM Threads                : total: 26 daemon: 7 non-daemon: 12 internal: 7
2013-05-23 12:55:50,671  INFO  scheduler_Worker-1  - executor with 20 threads

**Comment by Malax** [comment]
Closing this due to its age. Feel free to re-open should this issue still be relevant in 2022.
